- hosts: localhost
  gather_facts: no
  tasks: 
    - name: Waiting for the ssh to come up
      wait_for: port=22 host="{{ item }}" delay=10
      with_items:
          - "{{ groups['webserver'] }}"

- hosts: webserver
  remote_user: ec2-user
  become: true
  gather_facts: no
  roles:
     - web-server
